/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dv700.encrypter;

import org.junit.jupiter.api.Test;

import dv700.encrypter.app.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
}
