/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dv700.cipherApp.app;

public class App {

    public static void main(String[] args) {
        Main main = new Main();
        main.run();
    }
}
